gut-feeling.epub: Makefile *.md *.txt ./media/*
	pandoc -o $@ title.txt \
		cover.md \
		about.md \
		how-to-share-a-gut-feeling.md \
		privilege.md \
		five-whys.md \
		push-to-deploy.md \
		20-percent-rule.md \
		build-prototypes-instead-of-calling-a-meeting.md \
        wishful-thinking.md \
        walking-skeleton.md \
		zero-bug-policy.md \
		end.md