gut-feeling.pdf: Makefile *.md *.txt ./media/*
	pandoc \
		--pdf-engine=xelatex \
		--from markdown+tex_math_dollars+header_attributes \
		-o $@ \
		title.txt \
		cover.md \
		about.md \
		how-to-share-a-gut-feeling.md \
		privilege.md \
		five-whys.md \
		push-to-deploy.md \
		20-percent-rule.md \
		build-prototypes-instead-of-calling-a-meeting.md \
		Have-a-force-ranked-list-of-things-to-work-on.md \
        wishful-thinking.md \
		Ubiquitous-Language.md \
        walking-skeleton.md \
		TDD.md \
		zero-bug-policy.md \
		Event-Sourcing.md \
		Separate-workflows-through-events.md \
		CQRS.md \
		Hexagonal-Architecture.md \
		12-factor-app.md \
		No-monorepos.md \
		Short-lived-branches.md \
		Go-serverless.md \
		Use-TypeScript.md \
		Readable-Error-Messages.md \
		Do-not-proxy-Third-Party-RESTful-APIs.md \
		All-code-styleguides-must-be-enforceable-by-tools.md \
		Flow-with-the-dependencies.md \
		pre-written-meeting-minutes.md \
		Leadership.md \
		Books.md \
		Videos.md \
		Refs.md \
		end.md

